version: "3.7"
services:
  directus:
    image: directus/directus:10.12
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./blurhasher:/directus/extensions/directus-extension-blurhasher
      - ./blurhasher:/directus/node_modules/directus-extension-blurhasher
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
