name: Release CI/CD

on:
  push:
    branches: [semver-ci-cd]
  pull_request:
    branches: [semver-ci-cd]

jobs:
  permissions:
    contents: write

  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"

      - name: Change to project directory
        run: cd blurhasher

      - name: Install dependencies
        run: npm install
        working-directory: ./blurhasher

      - name: Run linter
        run: npm run lint
        working-directory: ./blurhasher

      - name: Build
        run: npm run build
        working-directory: ./blurhasher

      - name: Semantic Release
        run: npx semantic-release
        working-directory: ./blurhasher
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
